### ISSUE TITLE
Fullscreen control - alignment

### ISSUE THREAD

**Issue by DotNetFire** [kartena/Leaflet.Pancontrol#18]
Please add the following code to the stylessheet, so that the fullscreen control is aligned correctly:
``` css
/* Make the default zoom control align with the pan control. */ 
.leaflet-left.has-leaflet-pan-control .leaflet-control-fullscreen {
    position: relative;
    left: 24px;
}
.leaflet-right.has-leaflet-pan-control .leaflet-control-fullscreen {
    position: relative;
    right: 24px;
}
```
